image: Visual Studio 2015

configuration: Release
platform: AnyCPU

before_build:
- dotnet restore

build:
  project: FizzBuzz.sln
  verbosity: minimal

test_script:
- dotnet test ./test/FizzBuzz.Tests
