version: '1.0.{build}'

image: Visual Studio 2017

configuration: Release
platform: Any CPU

environment:
  nuget_user: user
  nuget_password:
    secure: JUwUVp6cuvFvLgLpkA6XUg==

nuget:
  account_feed: true

before_build:
- nuget restore
- dotnet restore

build_script:
- msbuild FizzBuzz.sln /t:build /p:configuration=%CONFIGURATION% /p:Platform="Any CPU"

after_build:
- ps: |
    (ls $env:APPVEYOR_BUILD_FOLDER -Recurse).Where{ $_.Extension -eq ".nuspec" }.ForEach{
      [xml]$xml = Get-Content $_.FullName
      $xml.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
      $xml.Save($_.FullName)
    }
    nuget pack FizzBuzz.nuspec -OutputDirectory artifacts

test_script:
- nunit3-console.exe ./test/FizzBuzz.Tests/bin/Release/net461/FizzBuzz.Tests.dll --result=myresults.xml;format=AppVeyor

artifacts:
- path: artifacts\**\*.*

deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/tknhs/api/v2/package
  api_key:
    secure: dEwVkKNIsCzeT9IZvMVnfTQuQVykh9xeQDzfJGfBI9U=
  skip_symbols: true
  artifact: /.*\.nupkg/
