image: Visual Studio 2015

configuration: Release
platform: Any CPU

before_build:
- nuget restore
- dotnet restore

build:
  project: FizzBuzz.sln
  verbosity: minimal

after_build:
- dotnet pack src/FizzBuzz -c %CONFIGURATION% --no-build -o artifacts

test_script:
- dotnet test ./test/FizzBuzz.Tests

on_finish:
- ps: (New-Object Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $env:APPVEYOR_BUILD_FOLDER\TestResult.xml))

artifacts:
- path: artifacts\**\*.*

deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/tknhs/api/v2/package
  api_key:
    secure: dEwVkKNIsCzeT9IZvMVnfTQuQVykh9xeQDzfJGfBI9U=
  skip_symbols: true
  artifact: /.*\.nupkg/