image: Visual Studio 2015

configuration: Release
platform: Any CPU

before_build:
- nuget restore
- dotnet restore

build:
  project: FizzBuzz.sln
  verbosity: minimal

test_script:
- dotnet test ./test/FizzBuzz.Tests
